#!/usr/bin/env node
/* Generates app/.env from the legacy PHP config (config.php + .env).
 * Safe to re-run: overwrites app/.env but preserves existing DATABASE_URL /
 * JWT_SECRET lines if present. Never prints secret values. */
const fs = require("fs");
const path = require("path");
const crypto = require("crypto");

const ROOT = process.env.FRONTEND_ROOT || path.resolve(__dirname, "..", "..");
const APP = path.resolve(__dirname, "..");

// ---- extract PHP config ----
const php = fs.readFileSync(path.join(ROOT, "config.php"), "utf8");
function phpDefault(name) {
  const m = php.match(new RegExp(`'${name}'\\s*=>\\s*'([^']*)'`));
  return m ? m[1] : "";
}
function phpBool(name) {
  const m = php.match(new RegExp(`'${name}'\\s*=>\\s*(true|false)`));
  return m ? m[1] : "";
}

// legacy .env key=value
const dotenv = {};
for (const line of fs.readFileSync(path.join(ROOT, ".env"), "utf8").split("\n")) {
  const i = line.indexOf("=");
  if (i > 0 && !line.trim().startsWith("#")) {
    dotenv[line.slice(0, i).trim()] = line.slice(i + 1).trim();
  }
}
function dv(name) {
  return dotenv[name] || "";
}

const firebaseKeys = ["apiKey", "authDomain", "projectId", "storageBucket", "messagingSenderId", "appId", "measurementId", "vapidKey"];
const fb = {};
for (const k of firebaseKeys) fb[k] = phpDefault(k);

let jwtSecret = "";
const existingPath = path.join(APP, ".env");
if (fs.existsSync(existingPath)) {
  const old = fs.readFileSync(existingPath, "utf8");
  const m = old.match(/^JWT_SECRET=(.+)$/m);
  if (m) jwtSecret = m[1];
  const db = old.match(/^(DIRECT_)?DATABASE_URL=.+$/m);
  if (db) jwtSecret += "\x00" + db[0]; // stash db urls too
}
if (!jwtSecret || !jwtSecret.includes("DATABASE_URL")) {
  // generate fresh secret if absent
  if (!jwtSecret) jwtSecret = crypto.randomBytes(48).toString("hex") + "\x00";
  if (!jwtSecret.includes("DATABASE_URL")) jwtSecret += "DATABASE_URL=\nDIRECT_DATABASE_URL=\n";
}
const [secret, dbUrl, directDbUrl] = jwtSecret.split("\x00");

const out = [];
const L = (k, v) => out.push(`${k}=${v}`);

L("# Generated by scripts/gen-env.cjs from legacy config.php + .env — review before use");
L("");
L("# Database (FILL IN when doing DB migration)");
L(dbUrl || "DATABASE_URL=");
L(directDbUrl || "DIRECT_DATABASE_URL=");
L("");
L("# Session");
L(`JWT_SECRET=${secret}`);
L("SESSION_TTL_DAYS=365");
L("");
L("# Firebase Admin SDK (server-side only)");
L(`FIREBASE_PROJECT_ID=${fb.projectId}`);
L(dv("FCM_CLIENT_EMAIL") ? `FIREBASE_CLIENT_EMAIL=${dv("FCM_CLIENT_EMAIL")}` : "FIREBASE_CLIENT_EMAIL=");
L(dv("FCM_PRIVATE_KEY") ? `FIREBASE_PRIVATE_KEY="${dv("FCM_PRIVATE_KEY").replace(/\n/g, "\\n")}"`.slice(0, 0) : "FIREBASE_PRIVATE_KEY=");
// private key written raw below to keep newlines escaped properly
out.pop();
out.push(dv("FCM_PRIVATE_KEY") ? `FIREBASE_PRIVATE_KEY="${dv("FCM_PRIVATE_KEY").split("\n").join("\\n")}"` : 'FIREBASE_PRIVATE_KEY=""');
L("");
L("# Firebase Web config (public by design)");
L(`FIREBASE_WEB_API_KEY=${fb.apiKey}`);
L(`FIREBASE_AUTH_DOMAIN=${fb.authDomain}`);
L(`FIREBASE_PROJECT_ID_PUBLIC=${fb.projectId}`);
L(`FIREBASE_STORAGE_BUCKET=${fb.storageBucket}`);
L(`FIREBASE_MESSAGING_SENDER_ID=${fb.messagingSenderId}`);
L(`FIREBASE_APP_ID=${fb.appId}`);
L(`FIREBASE_MEASUREMENT_ID=${fb.measurementId}`);
L(`VAPID_PUBLIC_KEY=${fb.vapidKey}`);
L("");
L("# SMS gateway (OneCodeSoft)");
L(`SMS_API_URL=${dv("ONECODESOFT_API_URL")}`);
L(`SMS_API_KEY=${dv("ONECODESOFT_API_KEY")}`);
L(`SMS_SENDER_ID=${dv("ONECODESOFT_SENDER_ID")}`);
L(`ONECODESOFT_METHOD=${dv("ONECODESOFT_METHOD")}`);
L("");
L("# Telegram bot relay");
L(`TELEGRAM_BOT_URL=${phpDefault("TELEGRAM_BOT_URL")}`);
L(`TELEGRAM_BOT_SECRET=${phpDefault("TELEGRAM_BOT_SECRET")}`);
L(`TELEGRAM_BOT_USERNAME=${phpDefault("TELEGRAM_BOT_USERNAME")}`);
L(`TELEGRAM_BOT_INSECURE_TLS=${phpBool("TELEGRAM_BOT_INSECURE_TLS") || "false"}`);
L("");
L("# Email reports");
L("REPORT_EMAIL_TO=");
L("RESEND_API_KEY=");
L("");
L("# Upload storage");
L("BLOB_READ_WRITE_TOKEN=");
L("");
L("# Request cleanup");
L(`AUTO_DELETE_DAYS=${phpDefault("AUTO_DELETE_DAYS") || "3"}`);
L("");
L("# Branding / site config");
L(`BRAND_NAME=${phpDefault("BRAND_NAME")}`);
L(`BRAND_SHORT=${phpDefault("BRAND_SHORT")}`);
L(`BRAND_TAGLINE=${phpDefault("BRAND_TAGLINE")}`);
L(`ORG_NAME=${phpDefault("ORG_NAME")}`);
L(`CONTACT_PHONE=${phpDefault("CONTACT_PHONE")}`);
L(`SITE_URL=${phpDefault("SITE_URL")}`);
L(`LOGO_PATH=${phpDefault("LOGO_PATH")}`);
L(`COLOR_PRIMARY=${phpDefault("COLOR_PRIMARY")}`);
L(`COLOR_PRIMARY_HOVER=${phpDefault("COLOR_PRIMARY_HOVER")}`);
L(`COLOR_BG_MAIN=${phpDefault("COLOR_BG_MAIN")}`);
L(`COLOR_THEME=${phpDefault("COLOR_THEME")}`);
L(`SOCIAL_FACEBOOK=${phpDefault("SOCIAL_FACEBOOK")}`);
L(`SOCIAL_TELEGRAM=${phpDefault("SOCIAL_TELEGRAM")}`);
L("");

fs.writeFileSync(existingPath, out.join("\n") + "\n", { mode: 0o600 });

// Gap report (names only, no values)
console.log("app/.env written (permissions 600). Gap report:");
const gaps = [];
for (const [k, v] of [
  ["DATABASE_URL", dbUrl], ["DIRECT_DATABASE_URL", directDbUrl],
  ["JWT_SECRET", secret],
  ["FIREBASE_CLIENT_EMAIL", dv("FCM_CLIENT_EMAIL")], ["FIREBASE_PRIVATE_KEY", dv("FCM_PRIVATE_KEY")],
  ["SMS_API_URL/KEY/SENDER", dv("ONECODESOFT_API_URL") && dv("ONECODESOFT_API_KEY") && dv("ONECODESOFT_SENDER_ID")],
  ["TELEGRAM_BOT_*", phpDefault("TELEGRAM_BOT_URL") && phpDefault("TELEGRAM_BOT_SECRET")],
  ["VAPID_PUBLIC_KEY", fb.vapidKey], ["FIREBASE_WEB_API_KEY", fb.apiKey],
]) {
  console.log(`  ${v ? "OK      " : "MISSING "} ${k}`);
}
console.log("\nNot yet available anywhere (need your input): REPORT_EMAIL_TO, RESEND_API_KEY, BLOB_READ_WRITE_TOKEN");
